meta_product_name: "Parentheze"
meta_title: "Parentheze - La nouvelle vie des parents"
meta_description: "Facilitez-vous la vie de parent, rencontrez-vous, échangez la garde des enfants et sortez!"
meta_image: "header_parentheze.jpg"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@parentheze"              # indispensable pour les Twitter Cards